### ISSUE TITLE
HDF5 versions 1 and 2; freepascal/Lazarus compatibility

### ISSUE THREAD

**Issue by neurolabusc** [CWBudde/PasHdf#1]
Hello
  Thanks for your work on this project that fills an important niche. I would like to make a few enhancement requests:

1.) Please add support for HDF5 version 0, this seems the most common version. For example, it is the default output for my version of matlab (attached below). It is also demonstrated in these other example datasets:
 https://github.com/UCSantaCruzComputationalGenomicsLab/hdf5/tree/master/tools/testfiles
 https://github.com/HDF-NI/hdf5.node/tree/master/test/examples
I have included links in my modified HdfFile.pas (attached) that describe the differences between the versions. My modifications (attached) are not complete, but they provide a skeleton to achieve this.

2.) It would be great if this were compatible with both Delphi as well as FreePascal. The attached file includes {$IFDEF FPC} that allows this.

[HdfFile.zip](https://github.com/CWBudde/PasHdf/files/1260193/HdfFile.zip)

**Comment by CWBudde** [comment]
I have merged the changes and adapted them. I also had a look at the specifications, but given the fact that it's already been a while since I had a look at it the last time, I can't help further so far.

The original specifications a very cluttered if documented at all. It's close to hacking to get deeper in interpreting the bytes.

Feel free to fork this project and implement reading of other versions and formats.
